fix empty cornerPoints and a never-ending call when image has no barcode on iOS
capawesome-team/capacitor-mlkit pull request #100
Opened 2023-11-23 12:01 UTC by nurfgun

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ v ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).

This improved two things :
- Includes raw cornerPoints in the result data of "readBarcodesFromImage" and "scan" on iOS instead of empty array.
- Returns empty data when there is no detection on readBarcodesFromImage instead of having a call hanging.

2023-11-24 07:40 UTC, nurfgun commented
did the same for android for missing corner points.

2023-11-24 08:31 UTC, robingenz requested changes
Please run `npm run changeset` to create a changeset.

2023-11-24 08:31 UTC, robingenz commented on packages/barcode-scanning/package.json
> +  "version": "5.3.1",
Please revert this change.

2023-11-24 08:31 UTC, robingenz commented on packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScannerHelper.java
> +        else if (cornerPoints != null) {
This also affects the `scan(...)` method and leads to invalid values there, as these would have to be normalized.
For now, my suggestion is to make this dependent on the `screenSize` parameter. If this parameter is set, corner points may only be returned normalized. I will improve this later.

```suggestion
        else if (cornerPoints != null && screenSize == null) {
```

Make sure that the `screenSize` parameter is `null` only for the `readBarcodesFromImage(...)` method.
Please also apply this to iOS.

2023-11-24 08:31 UTC, robingenz commented
@nurfgun Thank you for your contribution! 

> This improved two things :

Please create two seperate PRs. I will review this PR for #39.

2025-01-19 12:13 UTC, robingenz commented
Closed by #225

2025-01-19 12:13 UTC, closed without merging