fix: DispatchQueue for synchronizing the session configuration and start operations
capawesome-team/capacitor-mlkit pull request #214
Opened 2024-12-13 11:15 UTC by jimcase

This PR addresses synchronization issues reported on an [Apple Developer Forum thread](https://forums.developer.apple.com/forums/thread/743177), where users encountered NSGenericException due to premature execution of AVCaptureSession.startRunning(). The problem arises from startRunning() being called before the completion of commitConfiguration(), especially noted in iOS 17 and some iOS 16 devices.

To resolve this, we introduce a serial DispatchQueue for managing AVCaptureSession operations in a FIFO (First In, First Out) sequence. Configuration tasks are encapsulated within a synchronous block to ensure complete setup before proceeding. Following this, startRunning() is scheduled asynchronously, guaranteeing it executes only after the configuration is fully committed. This approach not only prevents the NSGenericException by ensuring proper sequence of operations but also maintains high performance and responsiveness of the application.## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).
- [ ] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

2024-12-16 08:19 UTC, robingenz requested changes
Please create your PR against `next` and not against `main`.

2024-12-16 08:19 UTC, robingenz commented on .changeset/forty-avocados-allow.md
> +Related PR [fix(barcode-scanning): add delay before starting camera session #188](https://github.com/capawesome-team/capacitor-mlkit/pull/188)
```suggestion
fix(ios): use queue for synchronizing the session configuration and start operations of the `scan(...)` method
```

2024-12-16 08:19 UTC, robingenz commented on packages/barcode-scanning/ios/Plugin/BarcodeScannerView.swift
> +
Please remove this empty line.

2024-12-18 11:39 UTC, jimcase commented on packages/barcode-scanning/ios/Plugin/BarcodeScannerView.swift
> +
done!

2025-01-08 11:16 UTC, robingenz commented
@jimcase Is this PR ready for review?

2025-01-08 11:20 UTC, jimcase commented
@robingenz Yes, its ready

2025-01-08 11:23 UTC, robingenz commented
@jimcase Please create your PR against the`next` branch and not against the `main` branch. Please also solve all possible merge conflicts.

2025-01-14 07:54 UTC, robingenz commented on .changeset/forty-avocados-allow.md
> +'@capacitor-mlkit/barcode-scanning': minor
```suggestion
'@capacitor-mlkit/barcode-scanning': patch
```

2025-01-14 09:48 UTC, robingenz commented
@jimcase Please merge the latest `origin/next` changes.

2025-01-15 15:02 UTC, merged

2025-01-15 15:02 UTC, robingenz commented
@jimcase Thank you!