feat: add @capacitor-mlkit/selfie-segmentation package
capawesome-team/capacitor-mlkit pull request #68
Opened 2023-09-02 11:24 UTC by trancee

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).

2023-09-02 13:14 UTC, robingenz commented
Do you want me to review it?

2023-09-02 13:26 UTC, trancee commented
> Do you want me to review it?

Yes, at least the Android implementation so far.

I was wondering if it is that helpful to return the segmentation mask as number array, and instead give an option to already apply this to the input image and return an output image as well?

2023-09-02 14:54 UTC, robingenz requested changes
LGTM! Only two small things.

2023-09-02 14:54 UTC, robingenz commented on packages/selfie-segmentation/android/build.gradle
> +        classpath 'com.android.tools.build:gradle:8.0.2'
Please revert this change so that we use the same Gradle version in all plugins. I will stay with `8.0.0` until the Capacitor team updates.

2023-09-02 14:54 UTC, robingenz commented on packages/selfie-segmentation/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/selfiesegmentation/SelfieSegmentationPlugin.java
> +            Boolean enableRawSizeMask = call.getBoolean("enableRawSizeMask", false);
Please add the `@default false` jsdoc tag to the `enableRawSizeMask` property in `definitions.ts.`

2023-09-02 15:02 UTC, robingenz commented
> > Do you want me to review it?
> 
> Yes, at least the Android implementation so far.
> 
> I was wondering if it is that helpful to return the segmentation mask as number array, and instead give an option to already apply this to the input image and return an output image as well?

@trancee Would you add a `confidence` option as a threshold and depending on that create the image or what do you have in mind?
But it looks good to me as it is for now.

2023-09-02 18:57 UTC, trancee commented
> @trancee Would you add a `confidence` option as a threshold and depending on that create the image or what do you have in mind? But it looks good to me as it is for now.

I am actually not sure yet. But I will keep it as is for now and maybe add something later if it is difficult to use in JavaScript.

2023-09-03 08:24 UTC, robingenz approved these changes

2023-09-03 08:24 UTC, merged